/** Derives the MHR left/right mirror of every pose parameter numerically and
 * writes src/dense/inference/mhr-mirror.js. For each parameter i (after the 6
 * root parameters) it finds the parameter j and sign s such that setting
 * j to s·δ produces the sagittal mirror image of setting i to δ.
 *
 *   node ml/body-sense/mhr_mirror.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { gunzipSync } from 'node:zlib';
import { createDecoderFromArrays, viewsFromManifest } from '../../src/dense/decoder/mhr-decoder.js';

const dir = new URL('../../public/dense/', import.meta.url);
const manifest = JSON.parse(readFileSync(new URL('mhr-lod3.json', dir)));
const bytes = gunzipSync(readFileSync(new URL('mhr-lod3.bin.gz', dir)));
const decoder = createDecoderFromArrays(manifest, viewsFromManifest(manifest, bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength)));
const joints = manifest.jointNames, params = manifest.modelParameterNames;
const swapName = name => name.replace(/(^|_)([lr])_/g, (_, pre, side) => `${pre}${side === 'l' ? 'r' : 'l'}_`);
const jointPair = joints.map(name => joints.indexOf(swapName(name)));
if (jointPair.some(i => i < 0)) throw new Error('A joint has no left/right counterpart');
const positions = q => decoder.decodeSkeleton(q).positions;
const zero = new Float32Array(params.length);
const mirrored = X => {
  const out = new Float64Array(X.length);
  for (let j = 0; j < joints.length; j++) { const k = jointPair[j]; out[j * 3] = -X[k * 3]; out[j * 3 + 1] = X[k * 3 + 1]; out[j * 3 + 2] = X[k * 3 + 2]; }
  return out;
};
const target = new Int16Array(params.length), sign = new Int8Array(params.length);
for (let i = 0; i < params.length; i++) {
  if (i < 6) { target[i] = i; sign[i] = 1; continue; }      // root: see mhr-flip.js
  const j = params.indexOf(swapName(params[i]));
  if (j < 0) throw new Error(`No mirror parameter for ${params[i]}`);
  const q = zero.slice(); q[i] = .3;
  const want = mirrored(positions(q));
  let best = null;
  for (const s of [1, -1]) {
    const r = zero.slice(); r[j] = s * .3;
    const X = positions(r); let error = 0;
    for (let k = 0; k < X.length; k++) error = Math.max(error, Math.abs(X[k] - want[k]));
    if (!best || error < best.error) best = { s, error };
  }
  if (best.error > 1e-4) throw new Error(`${params[i]} has no exact mirror (${best.error} m)`);
  target[i] = j; sign[i] = best.s;
}
const out = new URL('../../src/dense/inference/mhr-mirror.js', import.meta.url);
writeFileSync(out, `// Generated by ml/body-sense/mhr_mirror.mjs from ${manifest.binaryFile ?? 'mhr-lod3'} (${params.length} parameters).
// Left/right mirror image of a pose q: mirrored[MIRROR_TARGET[i]] = MIRROR_SIGN[i] * q[i].
// Root parameters (0-5) are handled in mhr-flip.js.
export const MIRROR_TARGET = Int16Array.from(${JSON.stringify(Array.from(target))});
export const MIRROR_SIGN = Int8Array.from(${JSON.stringify(Array.from(sign))});
`);
console.log('wrote', out.pathname, 'pairs', Array.from(target).filter((j, i) => j !== i).length, 'negated', Array.from(sign).filter(s => s < 0).length);
